### ISSUE TITLE
Login but says internal error?

### ISSUE THREAD

**Issue by scheung38** [scotch-io/meteor-slack#5]
How to change to another avatar?

Not sure what is the red badge always remaining at 0?

Whenever I tried to create new user says internal error?

I tried meteor reset. But still getting the same. commit in part4 can create new rooms but the final master cannot?

How to automatically scroll up whenever a new message appears instead of having to manually scroll up?

**Comment by d4nyll** [comment]
This is an imcomplete clone of Slack, purely as a teaching demo. So you can't change the avatar and the message count is there purely for aesthetic reasons.

On the [demo](http://scotch-slack4.meteor.com/) I am able to create a new user without an internal error. Are you able to look into the console (on the server) and copy the error message that's displayed?

**Comment by d4nyll** [comment]
I've updated the master branch now. It should scroll to the bottom of the message history whenever a new message is added.
