### ISSUE TITLE
The SCSS files

### ISSUE THREAD

**Issue by NinadNaik2811** [scotch-io/meteor-slack#6]
Hey I am new to meteor and scss so forgive me if I am asking something dumb but where can i get these SCSS files from which are included in global.css 
Thanks in advanced :)

**Comment by d4nyll** [comment]
Hey @NinadNaique it's not a dumb question at all! I really should have added the source files in the repository.

I've went through my storage drives but couldn't find the source files, so unfortunately the source file is lost :sob:

**Comment by NinadNaik2811** [comment]
Hey!! thanks anyways!! What you have done is making my life a lot easier as is
